base:
  project: winequality
  random_state: 9
  target_col: TARGET

data_source:
  source: actual_data\winequality.csv

load_data:
  raw_dataset: data\raw\winequality.csv

split_data:
  train_path: data\Processed\train_winequality.csv
  test_path: data\Processed\test_winequality.csv
  test_size: 0.2

estimators:
  Elastic_Net:
    params:
    #  alpha: 0.88
    # l1_ratio: 0.89
    #  alpha: 0.8
    #  l1_ratio: 0.9
    #  alpha: 0.9
    #  l1_ratio: 0.2
      alpha: 0.75
      l1_ratio: 0.3

model_dir: saved_models  

reports:
  params: reports\params.json
  scores: reports\scores.json

webapp_model_dir: prediction_service\model\model.joblib
